# Generated by Django 4.0.4 on 2022-06-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='opened',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
