# Generated by Django 4.0.4 on 2022-06-10 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_description_company_opened'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('resume', models.CharField(max_length=20)),
                ('transcript', models.CharField(max_length=20)),
                ('recommendation', models.CharField(max_length=20)),
                ('cover_letter', models.CharField(max_length=20)),
                ('requirements', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
