# Generated by Django 4.0.4 on 2022-06-13 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_field'),
        ('company', '0003_internjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume', models.FileField(null=True, upload_to='resume')),
                ('recommendation', models.FileField(null=True, upload_to='recommendation')),
                ('transcript', models.FileField(null=True, upload_to='transcript')),
                ('cover_letter', models.FileField(null=True, upload_to='cover_letter')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.internjob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
