# Generated by Django 4.0.4 on 2022-06-07 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middleName', models.CharField(max_length=200, null=True)),
                ('phoneNo', models.CharField(max_length=14, null=True)),
                ('school', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('yearOfStudy', models.CharField(max_length=10)),
                ('profilePic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
