# Generated by Django 4.0.4 on 2022-06-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='headline',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
