# Generated by Django 4.0.4 on 2022-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='field',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
